/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/global/header";
import ThemeProvider from "@/app/(frontend)/providers/theme";
import { SidebarCollapseProvider } from "@/app/(frontend)/providers/collapse-sidebar";
import Sidebar from "@/components/global/sidebar";

import { Toaster } from "@/components/ui/toaster";
import SessionProviderWrapper from "./providers/session.provider";

import ApolloProviderWrapper from "./providers/ApolloProviderWrapper";
const inter = Inter({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  antialiased`}>
        <SessionProviderWrapper>
          <ThemeProvider attribute="class" defaultTheme="dark">
            <SidebarCollapseProvider>
              <ApolloProviderWrapper>
                <Header />
                <div className="flex">
                  <Sidebar />

                  <main className="p-5 ml-[16rem] w-full">{children}</main>
                </div>
              </ApolloProviderWrapper>
            </SidebarCollapseProvider>
          </ThemeProvider>
        </SessionProviderWrapper>
        <Toaster />
      </body>
    </html>
  );
}
